export interface Voucher {
  _id: number
  date: string
  actorName: string
  prodName: string
  bgType: string
  wetPay: boolean
  smokePay: boolean
  hmu: boolean
  startTime: string
  endTime: string
  ndbStart: string
  lunchStart: string
  lunchEnd: string
  dinnerStart: string
  dinnerEnd: string
  numWardrobe: number
  formalWear: boolean
  policeWear: boolean
  pet: boolean
  golfClubs: boolean
  tennisRacquet: boolean
  luggage1: boolean
  luggage2: boolean
  camera: boolean
  skisPoles: boolean
  otherPropsAmt: number
  car: boolean
  trailer: boolean
  bicycle: boolean
  moped: boolean
  motorcycle: boolean
  policeMoto: boolean
  skatesOrSkateboard: boolean
  hazardPay: number
  otherBumps: number
  mileage: number
  tolls: number
  hrsWorked: number
  totalPay: number
}